MDBoxLayout:
    orientation: "horizontal"
    size_hint_y: .1
    MDLabel:
        id: name_header
        text: ""
        font_size: "32sp"
        pos_hint: {"top": 1}
    MDIconButton:
        icon: "chevron-left"
        pos_hint: {"y": .1}
        size_hint_y: .1
    MDFlatButton:
        text: "open all"
        pos_hint: {"y": .1}
        size_hint_y: .1
    MDIconButton:
        icon: "chevron-right"
        pos_hint: {"y": .1}
        size_hint_y: .1